import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency } from './utils';

export interface VerifiedReportSummary {
  income: number;
  spending: number;
  net: number;
  transactionCount: number;
  purchaseCount: number;
  deliveryCount: number;
}

export interface VerifiedReportInput {
  reportId: string;
  title: string;
  ownerName: string;
  ownerRole: string;
  ownerId: string;
  periodLabel: string;
  startDate: string;
  endDate: string;
  generatedAt: string;
  verificationCode: string;
  qrDataUrl?: string;
  summary: VerifiedReportSummary;
  rows: Array<Array<string | number>>;
}

export function generateVerifiedActivityReport(input: VerifiedReportInput) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;

  doc.setFontSize(22);
  doc.setTextColor(234, 88, 12);
  doc.text('Bwenge NEXUS', pageWidth / 2, 18, { align: 'center' });

  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(input.title.toUpperCase(), pageWidth / 2, 28, { align: 'center' });

  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(`Report ID: ${input.reportId}`, margin, 40);
  doc.text(`Owner: ${input.ownerName} (${input.ownerRole})`, margin, 46);
  doc.text(`Period: ${input.periodLabel}`, margin, 52);
  doc.text(`Date Range: ${input.startDate} to ${input.endDate}`, margin, 58);
  doc.text(`Generated: ${input.generatedAt}`, margin, 64);

  if (input.qrDataUrl) {
    doc.addImage(input.qrDataUrl, 'PNG', pageWidth - 48, 38, 32, 32);
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text('Scan to verify', pageWidth - 32, 74, { align: 'center' });
  }

  autoTable(doc, {
    startY: 82,
    head: [['Metric', 'Value']],
    body: [
      ['Income', `RWF ${formatCurrency(input.summary.income)}`],
      ['Spending', `RWF ${formatCurrency(input.summary.spending)}`],
      ['Net', `RWF ${formatCurrency(input.summary.net)}`],
      ['Transactions', input.summary.transactionCount],
      ['Purchases/Sales', input.summary.purchaseCount],
      ['Deliveries', input.summary.deliveryCount],
    ],
    theme: 'striped',
    headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
    styles: { fontSize: 9, cellPadding: 3 },
  });

  const rowsStart = ((doc as any).lastAutoTable?.finalY || 116) + 10;
  autoTable(doc, {
    startY: rowsStart,
    head: [['Date', 'Type', 'Description', 'Amount', 'Status']],
    body: input.rows.length
      ? input.rows.slice(0, 120)
      : [['-', 'No activity', 'No records found in this period', '-', '-']],
    theme: 'grid',
    headStyles: { fillColor: [234, 88, 12], textColor: [255, 255, 255] },
    styles: { fontSize: 8, cellPadding: 2 },
  });

  const footerY = doc.internal.pageSize.getHeight() - 18;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Verification Code: ${input.verificationCode}`, margin, footerY);
  doc.text('This report is computer-generated by Bwenge Nexus.', pageWidth / 2, footerY + 6, {
    align: 'center',
  });

  doc.save(`Bwenge_Report_${input.periodLabel.replace(/\s+/g, '_')}_${input.reportId}.pdf`);
}
